# Thymeleaf settings
spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"

# Spring application name
spring.application.name: "Etienne Bader"

# Static resources locations
spring:
  web:
    resources:
      static-locations:
        - "classpath:/static_resources/css/"
        - "classpath:/static_resources/js/"
        - "classpath:/static_resources/js/jquery-3.7.1.min.js/"
        - "classpath:/extension/icons/"
        - "classpath:/static_resources/images/"
        - "classpath:/extension/bootstrap-5.3.3/dist/css/"
        - "classpath:/extension/bootstrap-5.3.3/dist/js/"
